# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

include:
  - project: "dependabot-gitlab/dependabot-standalone"
    file: ".gitlab-ci.yml"


stages:
  - build
  - build-on-mr
  - dependabot

.dependabot-gitlab:
  stage: dependabot


build-job:
  image: python:3.11.3-bullseye
  stage: build
  script:
      - curl -fsSL https://deb.nodesource.com/setup_16.x | bash - && apt-get install -y nodejs
      - npm i -g aws-cdk
      - pip install -r requirements.txt
      - pip install -r requirements-dev.txt
      - cdk synth

pre-commit-job:
  image: python:3.11.3-bullseye
  stage: build
  script:
      - git init .
      - git add .
      - python3 -m pip install --upgrade pip
      - pip install -r cdk/stacks/requirements.txt
      - pre-commit run --files app.py
      - pre-commit run --files cdk/constructs/*.py
      - pre-commit run --files cdk/schemas/*.py
      - pre-commit run --files cdk/stacks/*.py
      - pre-commit run --files cdk/stages/*.py
      - pre-commit run --files cdk/stacks/services/*.py
      - pre-commit run --files cdk/stacks/plugins/*.py
      - pre-commit run --files cdk/stacks/plugins/pipeline_trigger/*.py
      - pre-commit run --files cdk/utils/*.py
      - pre-commit run --files cdk/tests/infrastructure/*.py

build-on-mr:
  image: python:3.11.3-bullseye
  stage: build-on-mr
  script:
      - curl -fsSL https://deb.nodesource.com/setup_16.x | bash - && apt-get install -y nodejs
      - npm i -g aws-cdk
      - pip install -r requirements.txt
      - pip install -r requirements-dev.txt
      - cdk synth
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
pre-commit-on-mr:
  image: python:3.11.3-bullseye
  stage: build-on-mr
  script:
      - git init .
      - git add .
      - python3 -m pip install --upgrade pip
      - pip install -r cdk/stacks/requirements.txt
      - pre-commit run --files app.py
      - pre-commit run --files cdk/constructs/*.py
      - pre-commit run --files cdk/schemas/*.py
      - pre-commit run --files cdk/stacks/*.py
      - pre-commit run --files cdk/stages/*.py
      - pre-commit run --files cdk/stacks/services/*.py
      - pre-commit run --files cdk/stacks/plugins/*.py
      - pre-commit run --files cdk/stacks/plugins/pipeline_trigger/*.py
      - pre-commit run --files cdk/utils/*.py
      - pre-commit run --files cdk/tests/infrastructure/*.py
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
