version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    auto-merge: true
    open-pull-requests-limit: 1
    open-security-pull-requests-limit: 1
  - package-ecosystem: pip
    directory: cdk/stacks
    schedule:
      interval: daily
    auto-merge: true
    open-pull-requests-limit: 1
    open-security-pull-requests-limit: 1
